/*  Auto generated by hypd.eastasian.lisp  */
#ifndef __EASTASIAN_UNICODE_HEADER__
#define __EASTASIAN_UNICODE_HEADER__

#include "unicode.h"

#define EastAsianTable_Size 1169

enum EastAsianType {
    EastAsian_error,
    EastAsian_N,
    EastAsian_A,
    EastAsian_H,
    EastAsian_W,
    EastAsian_F,
    EastAsian_Na,
    EastAsian_Size
};

struct eastasian_struct {
    unicode a, b;
    enum EastAsianType c;
};

extern unsigned EastAsianSymbol[EastAsian_Size];
extern const enum EastAsianType EastAsianAscii[0x80];
extern const struct eastasian_struct EastAsianTable[EastAsianTable_Size];
enum EastAsianType eastasian_symbol(unicode c);
unsigned eastasian_width(unicode c);
void init_eastasian(void);

#endif

